### ISSUE TITLE
Binary SpanContext injection/extraction

### ISSUE THREAD

**Issue by jbye** [openzipkin-contrib/brave-opentracing#35]
Hi.

Just wondering why Binary injection/extraction is not possible with brave-opentracing, while it is supported by opentracing-java?

**Comment by adriancole** [comment]
mainly because no-one seems to use it :) Are you using it? Which library?
(curious about the format)

**Comment by adriancole** [comment]
by use it I mean use Binary type

**Comment by jbye** [comment]
I'm using Thrift with its binary protocol. I was thinking about using the binary format to serialize/deserialize the span as the header of the thrift message.

**Comment by adriancole** [comment]
Cool so this is different than the enveloping approach in finagle then..
mind being explicit with how youd encode it? We would use this in a feature
test

**Comment by adriancole** [comment]
cc @felixbarny

**Comment by adriancole** [comment]
currently using b3 single format for this, available in brave-opentracing 0.34.0
