### ISSUE TITLE
Map "span.kind" tag as span.kind()

### ISSUE THREAD

**Issue by adriancole** [openzipkin-contrib/brave-opentracing#38]
We should map Map "span.kind" tag as span.kind() . We should not "span.kind" as a binary annotation as it clutters the UI with duplicate information.

cc @felixbarny

**Comment by jakerobb** [comment]
FWIW: taking into account the issue I just submitted (https://github.com/openzipkin/brave-opentracing/issues/39) might complicate this a little.
