### ISSUE TITLE
Empty service name in Zipkin when using brave-opentracing

### ISSUE THREAD

**Issue by kangur85** [openzipkin-contrib/brave-opentracing#41]
# Description
Empty service name in Zipkin when using brave-opentracing. Please refer to the screenshot below.

# How to replicate the issue
```java
public static void main(String[] args) throws InterruptedException {
        OkHttpSender sender = OkHttpSender.create("http://127.0.0.1:9411/api/v1/spans");
        AsyncReporter reporter = AsyncReporter.builder(sender).build();
        Tracing braveTracing = Tracing.newBuilder()
            .localServiceName("my-service")
            .reporter(reporter)
            .build();

        Tracer tracer = BraveTracer.create(braveTracing);
        try ( Span span0 = tracer.buildSpan("span-0")
            .withTag("description", "top level initial span in the original process")
            .start() ) {
            Thread.sleep(500);
            System.out.println("Done. Next step is to visit http://localhost:9411 and check service name.");
        }

        Thread.sleep(2000); 
    }
```

## Dependencies used
1. `brave-opentracing:0.20.0`
2. `opentracing-api:0.21.0`
3. `io.zipkin.brave:brave:4.2.0` (the newest checked as well)
4. `io.zipkin.reporter:zipkin-sender-okhttp3:0.10.0`

## Zipkin server
For test purposes, Zipkin is executed as follows:

```shell
java -jar zipkin-server-1.26.0-exec.jar
```
# Actual result
![screenshot](http://i.imgur.com/rkuaYLh.png)
### JSON

```json
[
  {
    "traceId": "7c7f770e7a66b439",
    "id": "7c7f770e7a66b439",
    "name": "span-0",
    "timestamp": 1495620160339364,
    "duration": 502318,
    "binaryAnnotations": [
      {
        "key": "description",
        "value": "top level initial span in the original process",
        "endpoint": {
          "serviceName": "my-service",
          "ipv4": "192.168.56.1"
        }
      }
    ]
  }
]
```

### `/trace` JSON

```json
{
  "timestamp": 1495637295369,
  "info": {
    "method": "POST",
    "path": "/api/v1/spans",
    "headers": {
      "request": {
        "content-encoding": "gzip",
        "content-type": "application/x-thrift",
        "content-length": "178",
        "host": "127.0.0.1:9411",
        "connection": "Keep-Alive",
        "accept-encoding": "gzip",
        "user-agent": "okhttp/3.8.0"
      },
      "response": {
        "X-Application-Context": "zipkin-server:shared:9411",
        "status": "200"
      }
    },
    "timeTaken": "153"
  }
}
```
# Expected result
I would expect service name "my-service" displayed on a bar.

**Comment by kangur85** [comment]
I found out that if `.withTag()` is not used, the example above works. 
Alternatively, calling `.withTag("span.kind", "client")` also makes the missing service label appear.

So, despite using of brave.Span#kind is optional, it somehow influences displayed service name.
Having said that, it may be an issue in [brave](https://github.com/openzipkin/brave).

**Comment by devinsba** [comment]
Interesting, I'm hoping to have time to look at stuff again starting next week. I'm moving and therefore super busy in and out of work

**Comment by adriancole** [comment]
this is sorted in a recent version of zipkin server (as was a javascript related issue). Upgrade your server and all should work. I verified by posting the span you sent.. excellent detail
