### ISSUE TITLE
Contract consistency between BraveTracer and opentracing-jaxrs

### ISSUE THREAD

**Issue by tutufool** [openzipkin-contrib/brave-opentracing#49]
Hi, 

Here's Brave's logic:

@Override public <C> SpanContext extract(Format<C> format, C carrier) {
    Extractor<TextMap> extractor = formatToExtractor.get(format);
    if (extractor == null) {
      throw new UnsupportedOperationException(format + " not in " + formatToExtractor.keySet());
    }
    TraceContextOrSamplingFlags result = extractor.extract((TextMap) carrier);
    TraceContext context = result.context() != null
        ? result.context()
        : brave4.newTrace(result.samplingFlags()).context();
    return BraveSpanContext.wrap(context);
  }

You'll find a SpanContext will return anyway. (No null value return)

While in:

https://github.com/opentracing-contrib/java-jaxrs/blob/release-0.0.9/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/ServerTracingFilter.java#L59

they have:

SpanContext extractedSpanContext = tracer.extract(Format.Builtin.HTTP_HEADERS,
                    new ServerHeadersExtractTextMap(requestContext.getHeaders()));

            Tracer.SpanBuilder spanBuilder = tracer.buildSpan(requestContext.getMethod())
                    .withTag(Tags.SPAN_KIND.getKey(), Tags.SPAN_KIND_SERVER);

            if (extractedSpanContext != null) {
                spanBuilder.asChildOf(extractedSpanContext);
            }

It seems they use null value as the semantic of "no parent span".

Should I consider it's somewhat contract conflict?

Thanks
Leon

**Comment by adriancole** [comment]
returning null is easier for us and makes sense. However, the actual interface isn't marked nullable in docs or annotations. Can you raise a PR upstream to correct this? Once this is formalized, I'd love to remove that code.

https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/Tracer.java#L95

**Comment by tutufool** [comment]
Sure, let me do it.
Thanks a lot!
