### ISSUE TITLE
Could you support span decorator?

### ISSUE THREAD

**Issue by tutufool** [openzipkin-contrib/brave-opentracing#51]
Hi, 

I may have some common tags in my app which I'd like framework guys take care of it instead of app guys.
For example:
1. when span started, I need to auto add a tag to indicate on which thread it's started.
2. when span finished, I need to auto add a tag to indicate on which thread it's closed.

I've tried composite mode (since most of your class impls are final) to do wrappers.
It turns out having MySpanBuilder(wrap BraveSpanBuilder) to do decoration after startActive/startManual is OK.
But it's kind of hard for me to add a hook on finish. (since the finish() is conditionally executed in deactivate()).

So, I'm thinking whether you can provide an advanced overload builder method to use like:

BraveTracer.create(Tracing brave, SpanDecorator decorator);

while:

interface SpanDecorator{
 void afterStart(BaseSpan span);
 void beforeFinish(BaseSpan span);
}

Let me know if it's reasonable or you may have some other work around.

Thanks a lot!

Leon

**Comment by adriancole** [comment]
Thanks for the note. We've had some similar requests upstream just haven't
followed through (mainly waiting for more requests).

Might make sense to use a callback on brave's SpanCustomizer type as this
won't accidentally lead to someone messing up the lifecycle or being
tempted to.

ex onStart(SpanCustomizer span)

**Comment by tutufool** [comment]
I guess the reason you propose SpanCustomizer interface is because it hides lifecycle method like finish().
However, BaseSpan does not contain lifecylcle method as well, and it's purely opentracing api.

If we use SpanCustomizer as callback input, then user is forced to know more about brave.
According to my experience on using brave-opentracing, the only brave thing I use is BraveTracer.
All other brave things are completely hide to me, and I only need to use pure opentracing api.

**Comment by adriancole** [comment]
>
> If we use SpanCustomizer as callback input, then user is forced to know
> more about brave.
> According to my experience on using brave-opentracing, the only brave
> thing I use is BraveTracer.
> All other brave things are completely hide to me, and I only need to use
> pure opentracing api.
>
Customization like this isn't an OpenTracing api, anyway, right? You are
talking about a custom hook. Also are you expecting users to interact with
this? seems pretty low-level if it is applying to all spans.

**Comment by tutufool** [comment]
OK, then let's go with SpanCustomizer

**Comment by adriancole** [comment]
This issue was moved to openzipkin/brave#529
