### ISSUE TITLE
`SpanBuilder#buildManual()` should infer `CHILD_OF` reference from `ActiveSpanSource#activeSpan()`, if not set explicitly

### ISSUE THREAD

**Issue by yskopets** [openzipkin-contrib/brave-opentracing#56]
#### Issue

`Span` created by via `SpanBuilder#buildManual()` should have a `CHILD_OF` reference to `ActiveSpanSource#activeSpan()`, if not set explicitly.

E.g., the following code should result in a nested `Span` rather than a new root 
```
tracer.buildSpan("nested operation").startManual()
```

As a result, it's not possible to replace `jaeger-client` with `brave-opentracing` without change of semantics. 

#### Observed Behaviour

`tracer.buildSpan("nested operation").startManual()` starts a new `Trace`

#### Expected Behaviour

According to  https://gitter.im/opentracing/public :

> @hypnoce to @yskopets : the startManual method behave the same as startActive regarding the implicit childof.
> The [documentation is explicit](https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/Tracer.java#L192) about this. And the startActive documentation is pretty explicit when it adds the parent to the newly created span
>>>

They also recommend to look at [MockTracer](https://github.com/opentracing/opentracing-java/blob/master/opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java#L285) for clarification how API is expected to be implemented.

#### More context

Apparently, `jaeger-client` DOES infer `CHILD_OF` reference from `ActiveSpanSource#activeSpan()` - see https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/com/uber/jaeger/Tracer.java#L376

But, `brave-opentracing` does NOT - see https://github.com/openzipkin-contrib/brave-opentracing/blob/master/src/main/java/brave/opentracing/BraveSpanBuilder.java#L118

#### Affected version

0.23.0

**Comment by adriancole** [comment]
Personally I find it strange that the active span source is in use in the
thing that is startManual, and is an alternative to startActive. The docs
around this are somewhat of a run through the woods. Looking at a mock
tracer for behavior is symptomatic of missing interop tests.

None of above is new.

If anyone wants to meet this contract, please raise a PR. Thanks for
reporting this

**Comment by adriancole** [comment]
Also, please confirm this behavior will be the same in whatever 0.31
final will be (guessing by the response you got that it will)

**Comment by adriancole** [comment]
https://github.com/openzipkin-contrib/brave-opentracing/pull/57 makes it work as described and backfills tests
