### ISSUE TITLE
BraveSpanBuilder.addReference(???, null) throws NPE

### ISSUE THREAD

**Issue by bhanafee** [openzipkin-contrib/brave-opentracing#63]
BraveSpanBuilder.addReference throws NPE if the referencedContext parameter is null. Per the Javadoc on io.opentracing.Tracer.SpanBuilder, this should be a noop.

Same issue with the asChildOf convenience methods.

**Comment by adriancole** [comment]
strange api decision. thanks for raising the issue

**Comment by adriancole** [comment]
ps this was changed in the recent RC, so we shouldn't cut this without bumping to latest  https://github.com/opentracing/opentracing-java/commit/3192429cee1d142759bc0e01da7d702bdaa22375
