### ISSUE TITLE
Add tls support

### ISSUE THREAD

**Issue by bputt** [openzipkin-contrib/brave-opentracing#75]
When setting up the zipkin endpoint, it'd be helpful to enable TLS

```OkHttpSender.create("https://127.0.0.1:9411/api/v2/spans")```

Ideally, we could pass in a jks/pkcs12 cert, password, and a CA bundle

**Comment by bputt** [comment]
Referencing https://github.com/openzipkin/brave/issues/691 as that should be a dependency

**Comment by adriancole** [comment]
wrong project zipkin-reporter-java is what you want
