### ISSUE TITLE
Behavior of  BraveScopeManager.active()

### ISSUE THREAD

**Issue by tutufool** [openzipkin-contrib/brave-opentracing#76]
Hi, 

I'm not quite sure this is an issue, since I don't know where is a better place to ask question :)

In BraveScopeManager:

```
  BraveSpan currentSpan() {
    BraveScope scope = currentScopes.get().pollFirst(); --- not sure if it should be peekFirst()?
    if (scope != null) {
      return scope.span();
    } else {
      brave.Span braveSpan = tracer.currentSpan();
      if (braveSpan != null) {
        return new BraveSpan(tracer, braveSpan, BraveSpan.EMPTY_ENDPOINT);
      }
    }
    return null;
  }
```

If I call active() multiple times, only the first call benefits from currentScopes.get().
Others will lead to new BraveSpan() creation.

(I guess the only reason that we have currentScopes is to avoid object creation, considering the fact that CurrentTraceContext already handle threadlocal things)

Also,  maybe LinkedList is more efficient than ArrayDeque when do stack push/pop.

Thanks

Leon

**Comment by adriancole** [comment]
>    BraveScope scope = currentScopes.get().pollFirst(); --- not sure if it should be peekFirst()?

I think this is a bug. can you raise a PR?

**Comment by tutufool** [comment]
PR issued.

Btw, do you think we can change deregister to:

```
  void deregister(BraveScope span) {
	Deque<BraveScope> scopeStack = currentScopes.get();
	if(span.equals(scopeStack.peekFirst())){
		scopeStack.pollFirst();
	}else {
		//No op or throw exception
	}
    
  }
```

If BraveSpan carry on creation thread id, then we can provide more error info for the abnormal operation.

**Comment by adriancole** [comment]
yes so in brave normally we have this StrictCurrentTraceContext, you could
consider adding a flag or writing some FINE log level with a
java.util.logger

**Comment by tutufool** [comment]
By "adding a flag", do you suggest to allow user to control the "action against abnormal operation" by providing some configuration?

For example, a configurable flag/enum can be passed to BraveScopeManager via BraveTracer.Builder.
So user can enforce different behavior for Dev/QA/Prod.

And the deregsiter could be something like:

```
  void deregister(BraveScope span) {
	Deque<BraveScope> scopeStack = currentScopes.get();
	if(span.equals(scopeStack.peekFirst())){
		scopeStack.pollFirst();
	}else {
		if(suppressBadOperation){
                    //log with FINE level
                }else{
                    //throw exception 
                }
	}
    
  }


```

I can submit another PR for this change if we're on the same page.

**Comment by tutufool** [comment]
OK, feel free to release the bugfix. And I'll submit another PR based on your suggestion.

**Comment by adriancole** [comment]
release-0.30.2 on the way. thanks!

**Comment by tutufool** [comment]
Could you please help review the PR:
https://github.com/openzipkin-contrib/brave-opentracing/pull/78

Maybe a little over designed, since I found brave's SpanInScope does not handle the "mismatch" case as well.

**Comment by tutufool** [comment]
@adriancole just a reminder for the PR :)

**Comment by adriancole** [comment]
I am going away for a while. maybe someone else who is involved can look at
it.

**Comment by adriancole** [comment]
opentracing 0.33 removes this method
