### ISSUE TITLE
Client span should be remote service span's parent

### ISSUE THREAD

**Issue by jerryjxj** [openzipkin-contrib/brave-opentracing#8]
In the README.md, a client span will be automatically created when **tracer.inject()** is called. And it will be a child of span2. Afterwards, the headers injected will be passed to the remote server. The span created by remote server will be a child of span2 instead of the client span.

Root cause:
In BraveTrcer.inject(),   super.inject(spanContext, format, carrier) is called. The spanContext is span2. It should be client span.

**Comment by michaelsembwever** [comment]
See https://github.com/opentracing/opentracing-java/pull/71 and https://github.com/openzipkin/brave-opentracing/pull/10

**Comment by adriancole** [comment]
readme example has to change because the api has changed a lot since it was written
