### ISSUE TITLE
BraveScopeManager.active() and opentracing-jaxrs

### ISSUE THREAD

**Issue by jmif** [openzipkin-contrib/brave-opentracing#82]
Hi there,

We're having some issues with closing Scopes / Spans with opentracing-jaxrs.  This is related to https://github.com/opentracing-contrib/java-jaxrs/issues/87 and I'm hoping to get your input on the issue with respect to BrowserScopeManager / BrowserScopeManager.active()

At a high level (more details in referenced issue) [the JAXRS filter tries to close the current scope at the end of the request](https://github.com/opentracing-contrib/java-jaxrs/blob/5407a450d5564752b637b7c56267c3a938804e3f/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/SpanFinishingFilter.java#L64) and it grabs the current scope from the BraveTracer's BraveScopeManager [here](https://github.com/openzipkin-contrib/brave-opentracing/blob/77905e16c62a4ac4b8b051b212ee6077cb4966a4/src/main/java/brave/opentracing/BraveScopeManager.java#L47).

It then attempts to close the scope however the Scope returned from the BraveScopeManager has a noop close method.  This results in the scope not being closed and being used across requests.

Is this the expected behavior of active() (seems to be given the comment on the method)?  If so what is the best way to get the active scope and close it in this context?

**Comment by adriancole** [comment]
please file a bug to the jaxrs code. not only is that style of inteception
problematic (why brave moved to servlet filter + decoration for jax-rs),
but it is also unnecessary to use implicits to close a scope. using an
attribute is more reliable. There's a lot of bad instrumentation in
opentracing

**Comment by adriancole** [comment]
Here's the last code we used to ensure you don't have to use implicits
to close a scope
https://github.com/openzipkin/brave/commit/9d98d569940c4e68c834a8ada4fe70d51912e2eb#diff-27b317da912256b195ad886eac72f9f1L72

and here's why we removed that code in general
https://github.com/openzipkin/brave/tree/master/instrumentation/jaxrs2#why-dont-we-use-containerresponsefilter

**Comment by pavolloffay** [comment]
Agree that it's safer to pass the span around in attribute. Actually the scope in this case.

Is there any reason why `BraveScopeManager.active().close()` is noop? I don't think it complies with OpenTracing API. It will cause problems in other use-cases.

**Comment by pavolloffay** [comment]
This is also related to https://github.com/opentracing/opentracing-java/issues/267 and

**Comment by adriancole** [comment]
the opentracing api is both wrong and underspecified.

refer to reactive streams for an example of a properly specified api. it
should be a bug to close a scope from an alternate thread. the api is wrong
as it encourages doing this.

**Comment by adriancole** [comment]
while still thrashing there seems to be some hope that the api will be corrected https://github.com/opentracing/opentracing-java/issues/267#issuecomment-408409435

**Comment by rogueai** [comment]
Hi guys, I'd like to add to this issue both to try to understand an issue I'm facing, and to figure out a proper fix for that. 
I'm using spring messaging in my project, and it seems their OpenTracingChannelIntercpetor tries to close the scope after the message is sent, see [OpenTracingChannelInterceptor code here](https://github.com/opentracing-contrib/java-spring-messaging/blob/a0d1a30b63cbda984843070e69336a272cf676fc/opentracing-spring-messaging/src/main/java/io/opentracing/contrib/spring/integration/messaging/OpenTracingChannelInterceptor.java#L94)
So it looks like this is allowed by the OpenTracing spec, now the fact that in brave opentracing this is a No-op, that leaves my spans open across messages and I never get any tracing for them.
I tried to put a fix for that by caching the scopes in the interceptor when the spans start, but it does look like a hack to me, plus I'm worried about messing up the scopes.

Do you have suggestions on that? Can I achieve the same result without overriding their interceptor, or perhaps there's a better way to handle that?

Thanks.

**Comment by adriancole** [comment]
file a bug on their side. opentracing isn't a real spec

>

**Comment by adriancole** [comment]
opentracing 0.33 removes this method
