### ISSUE TITLE
Interface for customize traceId, even SpanId

### ISSUE THREAD

**Issue by cula** [openzipkin-contrib/brave-opentracing#97]
This is not an issue but some kind of requirement.
I'm integrating brave-opentracing and I have a requirement from storage team that timstamps should be encoded into traceId, which will fasten querying a lot.
I go through the code (0.33.7) and find no interface for doing this.

Currently, my workaround is coping `brave.opentracing.BraveSpanBuilder` and override the `start` function by something like the following:
```
 span = scopedBraveTracer.newTrace();
```
to
```
SpanContext mySpanContext = produceMySpanContext();

 span = scopedBraveTracer.toSpan(mySpanContext);
```

And event worse, I have to copy the `BraveSpanBuilder` code instead of `extend` it because it's `final`.

This is not a good implement but is the only way I found.

Is there any recommendation about this?

**Comment by cula** [comment]
How about a tweek version, just removing `final` from the class defination.

**Comment by adriancole** [comment]
If you are using `Tracing.builder.traceId128Bit(true)` the ids are already sortable by epoch seconds.

To manually control, closest you can do is use `Tracer.nextSpan(TraceContextOrSamplingFlags.create(TraceIdContext))` with the trace ID you externally manage, or you can use an extractor similarly.

A change to the ID generation process isn't likely to happen here, if anything would be in the main brave project
